### ISSUE TITLE
Use args4j to parsing the arguments 

### ISSUE THREAD

**Issue by alepuzio** [alepuzio/buildCSS#14]

**Comment by alepuzio** [comment]
Buidl ok, but I receive an horrible exception when I run the bat


> Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
>         at java.lang.Class.getDeclaredMethods0(Native Method)
>         at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
>         at java.lang.Class.getMethod0(Class.java:2866)
>         at java.lang.Class.getMethod(Class.java:1676)
>         at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
> Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>         ... 6 more
